### ISSUE TITLE
Unable to see cpu temps and adjust fan curve accordingly

### ISSUE THREAD

**Issue by 2Fac3** [Danielv123/serverManager#68]
I'm running a R720xd with Idrac7 Firmware 2.65.65.65 I am able to see the inlet and exhaust temps but my cpu temps do not show up.
If I run `ipmitool -I lanplus -H {ipaddress} -U root -P calvin sensor`   
it will spit out all the senor info and I can see my cpu temps there.

I did notice this error

Error: Command failed: ipmitool -I lanplus -H {ipaddress} -U root -P calvin sensor
at ChildProcess.exithandler (child_process.js:383:12)
at ChildProcess.emit (events.js:400:28)
at maybeClose (internal/child_process.js:1088:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5) {
killed: false,
code: null,
signal: 'SIGSEGV',
cmd: 'ipmitool -I lanplus -H {ipaddress} -U root -P calvin sensor'

**Comment by Danielv123** [comment]
I believe this should have been fixed in the latest version of the image. Please reopen if that is not the case.
